#!/usr/bin/env bash
# Regenerate FILE-MAP.md -- an index of every file grouped by folder, with each
# folder's "One job" line from its CONTEXT.md. Generated, never hand-edited
# (ICM invariant 9). Run from anywhere in the repo:  bash ops/scripts/build-file-map.sh
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
OUT="FILE-MAP.md"

# Tracked + new (not-yet-committed) files, respecting .gitignore (so node_modules,
# .next, .venv, __pycache__ are excluded automatically).
files() { git ls-files --cached --others --exclude-standard; }

{
  echo "# FILE-MAP (generated)"
  echo
  echo "Index of every file, grouped by folder, with each folder's one-job line."
  echo "Generated by \`ops/scripts/build-file-map.sh\` -- do not hand-edit (ICM invariant 9)."
  echo "Regenerate after adding or moving files."
  echo

  files() { git ls-files --cached --others --exclude-standard; }
  files | xargs -n1 dirname | sort -u | while IFS= read -r dir; do
    if [ "$dir" = "." ]; then title="(root)"; ctx="CONTEXT.md"; else title="$dir/"; ctx="$dir/CONTEXT.md"; fi
    echo
    echo "### $title"
    if [ -f "$ctx" ]; then
      job=$(grep -m1 -iE "^One job:" "$ctx" 2>/dev/null || true)
      [ -n "$job" ] && echo "$job"
    fi
    files | while IFS= read -r f; do
      if [ "$(dirname "$f")" = "$dir" ]; then echo "- \`$(basename "$f")\`"; fi
    done
  done
} > "$OUT"

echo "wrote $OUT ($(files | wc -l | tr -d ' ') files indexed)"
